FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache \
    bash \
    ca-certificates \
    git \
    libpcap \
    libpcap-dev \
    build-base

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG MAIN_PATH
CMD ["sh", "-c", "echo Running $MAIN_PATH && go run $MAIN_PATH"]
