# =========================
# مرحلة البناء (Builder)
# =========================
FROM golang:1.24-alpine AS builder

# تثبيت متطلبات CGO + libpcap
RUN apk add --no-cache \
    gcc \
    musl-dev \
    libpcap-dev

WORKDIR /app

# تحميل الاعتمادات
COPY go.mod go.sum ./
RUN go mod download

# نسخ الكود
COPY . .

# بناء السيرفر (CGO مفعّل بسبب gopacket/pcap)
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
    go build -o server ./cmd

# =========================
# مرحلة التشغيل (Runtime)
# =========================
FROM alpine:latest

# libpcap مطلوب وقت التشغيل
RUN apk add --no-cache libpcap

WORKDIR /app

# نسخ binary من مرحلة البناء

RUN chmod +x /app/server

# تشغيل السيرفر
CMD ["./server"]

