// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/gcpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Entries       []string               `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBatch) Reset() {
	*x = DataBatch{}
	mi := &file_proto_gcpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBatch) ProtoMessage() {}

func (x *DataBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBatch.ProtoReflect.Descriptor instead.
func (*DataBatch) Descriptor() ([]byte, []int) {
	return file_proto_gcpc_proto_rawDescGZIP(), []int{0}
}

func (x *DataBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *DataBatch) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DataBatch) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_proto_gcpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gcpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_gcpc_proto_rawDescGZIP(), []int{1}
}

func (x *BatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_gcpc_proto protoreflect.FileDescriptor

const file_proto_gcpc_proto_rawDesc = "" +
	"\n" +
	"\x10proto/gcpc.proto\x12\tanalytics\"\\\n" +
	"\tDataBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x18\n" +
	"\aentries\x18\x03 \x03(\tR\aentries\"C\n" +
	"\rBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2S\n" +
	"\x10AnalyticsService\x12?\n" +
	"\rReceivedBatch\x12\x14.analytics.DataBatch\x1a\x18.analytics.BatchResponseB\x1aZ\x18LM10/DataProcessor/protob\x06proto3"

var (
	file_proto_gcpc_proto_rawDescOnce sync.Once
	file_proto_gcpc_proto_rawDescData []byte
)

func file_proto_gcpc_proto_rawDescGZIP() []byte {
	file_proto_gcpc_proto_rawDescOnce.Do(func() {
		file_proto_gcpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gcpc_proto_rawDesc), len(file_proto_gcpc_proto_rawDesc)))
	})
	return file_proto_gcpc_proto_rawDescData
}

var file_proto_gcpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gcpc_proto_goTypes = []any{
	(*DataBatch)(nil),     // 0: analytics.DataBatch
	(*BatchResponse)(nil), // 1: analytics.BatchResponse
}
var file_proto_gcpc_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.ReceivedBatch:input_type -> analytics.DataBatch
	1, // 1: analytics.AnalyticsService.ReceivedBatch:output_type -> analytics.BatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gcpc_proto_init() }
func file_proto_gcpc_proto_init() {
	if File_proto_gcpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gcpc_proto_rawDesc), len(file_proto_gcpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gcpc_proto_goTypes,
		DependencyIndexes: file_proto_gcpc_proto_depIdxs,
		MessageInfos:      file_proto_gcpc_proto_msgTypes,
	}.Build()
	File_proto_gcpc_proto = out.File
	file_proto_gcpc_proto_goTypes = nil
	file_proto_gcpc_proto_depIdxs = nil
}
